FROM openjdk:17

WORKDIR /opt/jboss
ARG WILDFLY_VERSION

ADD wildfly-${WILDFLY_VERSION}.tar.gz .
RUN mv wildfly-${WILDFLY_VERSION} wildfly

ENV WILDFLY_VERSION=${WILDFLY_VERSION}
ENV LAUNCH_JBOSS_IN_BACKGROUND=true

EXPOSE 8080

RUN chmod +x "/opt/jboss/wildfly/bin/standalone.sh"

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
