services:
  quarkus:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    environment:
        - QUARKUS_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - wildfly-network
    env_file:
      - .env
  pg:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - wildfly-network
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data:Z
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pg
      POSTGRES_DB: studs
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
volumes:
  pg-data:

networks:
  wildfly-network:
    driver: bridge
